apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp
    namespace: final
    labels:
        app: employees
spec:
    replicas: 3
    selector:
        matchLabels:
            app: employees
    template:
        metadata:
            labels:
                app: employees
        spec:
            containers:
            -   name: webapp
                image: 407373101635.dkr.ecr.us-east-1.amazonaws.com/project-app:e4d41d0f96
                env:
                    -   name: DBHOST
                        value: "10.244.0.6"
                    -   name: DBPORT
                        value: "3306"
                    -   name: DATABASE
                        value: "employees"
                    -   name: DBUSER
                        valueFrom:
                            secretKeyRef:
                                name: db-secrets
                                key: user
                    -   name: DBPWD
                        valueFrom:
                            secretKeyRef:
                                name: db-secrets
                                key: password
                    -   name: GROUPNAME 
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: groupName
                    -   name: SLOGAN
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: slogan
                    -   name: IMAGEURL
                        valueFrom:
                            configMapKeyRef:
                                name: app-config
                                key: imageURL
                ports:
                    - containerPort: 8080
            dnsPolicy: ClusterFirst
            restartPolicy: Always