apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: final
  labels:
    app: employees
spec:
    type: LoadBalancer
    ports:
    -   protocol: TCP
        name: webapp
        port: 81
        targetPort: 81
    selector:
        app: employees