apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: final
  labels:
    app: employees
spec:
    type: NodePort
    ports:
    -   port: 81
        targetPort: 81
        nodePort: 30000
    selector:
        app: employees