apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi